add_newline = true

prompt_order = [
  "username",
  "hostname",
  "directory",
  "git_branch",
  "git_state",
  "git_status",
  "golang",
  "kubernetes",
  "nix_shell",
  "memory_usage",
  "aws",
  "cmd_duration",
  "jobs",
  "battery",
  "line_break",
  "time",
  "character",
]

[character]
symbol = "➜"

[cmd_duration]
style = "bold red"

[conda]
disabled = true

[directory]
style = "bold blue"

[dotnet]
disabled = true

[env_var]
disabled = true

[golang]
disabled = false

[git_state]
progress_divider = " off "

[memory_usage]
show_percentage = false
threshold = -1
symbol = "using "
style = "bold dimmed black"
disabled = false

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[time]
style = "bold dimmed black"
format = "%H:%M:%S"
disabled = false

[username]
disabled = false
show_always = true
style_root = "bold red"
style_user = "bold green"